# Generated by Django 5.0.6 on 2024-07-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_patient_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date',
        ),
    ]
