# Generated by Django 5.0.6 on 2024-07-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_medicalrecord_diagnosis_medicalrecord_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='prescription',
        ),
    ]
