# Generated by Django 5.0.6 on 2024-07-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_patient_slot_patient_slot_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='slot_date_time',
        ),
        migrations.AddField(
            model_name='patient',
            name='slot',
            field=models.CharField(blank=True, choices=[('9-10', '9-10'), ('10-11', '10-11'), ('11-12', '11-12'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('4-5', '4-5')], max_length=5, null=True),
        ),
    ]
