# Generated by Django 5.0.6 on 2024-07-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_patient_slot_date_time_patient_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
