# Generated by Django 5.0.6 on 2024-07-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='appointment_documents/'),
        ),
    ]
