# Generated by Django 5.0.6 on 2024-07-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('missed', 'Scheduled'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='scheduled', max_length=20),
        ),
    ]
