# Generated by Django 5.0.6 on 2024-07-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_appointment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='description_file',
            field=models.FileField(blank=True, null=True, upload_to='appointment_descriptions/'),
        ),
    ]
