# Generated by Django 5.0.6 on 2024-07-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_appointment_description_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicalrecord',
            unique_together={('appointment',)},
        ),
    ]
